const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getRides: () => ipcRenderer.invoke('get-rides'),
  getActivities: () => ipcRenderer.invoke('get-activities'),
  deleteRide: (id) => ipcRenderer.invoke('delete-ride', id),
  updateRide: (id, data) => ipcRenderer.invoke('update-ride', id, data),
  importGPX: () => ipcRenderer.invoke('import-gpx'),
  importGpx: () => ipcRenderer.invoke('import-gpx'),
  addManualActivity: (data) => ipcRenderer.invoke('add-manual-activity', data),
  getUser: () => ipcRenderer.invoke('get-user'),
  saveUser: (userData) => ipcRenderer.invoke('save-user', userData),
  trainML: (payload) => ipcRenderer.invoke('train-ml', payload),
  getHealthMetrics: () => ipcRenderer.invoke('get-health-metrics'),
  addHealthMetric: (m) => ipcRenderer.invoke('add-health-metric', m),
  updateHealthMetric: (id, updates) => ipcRenderer.invoke('update-health-metric', id, updates),
  deleteHealthMetric: (id) => ipcRenderer.invoke('delete-health-metric', id),
  getGears: () => ipcRenderer.invoke('get-gears'),
  addGear: (gearData) => ipcRenderer.invoke('add-gear', gearData),
  updateGear: (id, updates) => ipcRenderer.invoke('update-gear', id, updates),
  assignGearToActivities: (gearId) => ipcRenderer.invoke('assign-gear-to-activities', gearId),
  predictGearService: (gearId) => ipcRenderer.invoke('predict-gear-service', gearId),
  getGearParts: (gearId) => ipcRenderer.invoke('get-gear-parts', gearId),
  addGearPart: (gearId, part) => ipcRenderer.invoke('add-gear-part', gearId, part),
  replaceGearPart: (partId, removedAt, removedKm, newPart) => ipcRenderer.invoke('replace-gear-part', partId, removedAt, removedKm, newPart),
  trainGearML: (sample) => ipcRenderer.invoke('train-gear-ml', sample),
  predictGearML: (gearId) => ipcRenderer.invoke('predict-gear-ml', gearId),
  exportGearPartsCSV: (gearId) => ipcRenderer.invoke('export-gear-parts-csv', gearId),
  trainGearMLModel: (opts) => ipcRenderer.invoke('train-gear-ml-model', opts),
  getGearMLModel: (gearId) => ipcRenderer.invoke('get-gear-ml-model', gearId),
  deleteGear: (id) => ipcRenderer.invoke('delete-gear', id),
  resetGear: (id) => ipcRenderer.invoke('reset-gear', id),
  getGearAnalytics: () => ipcRenderer.invoke('get-gear-analytics'),
  getFitnessForm: () => ipcRenderer.invoke('get-fitness-form'),
  getFitnessHistory: () => ipcRenderer.invoke('get-fitness-history'),
  getAdvancedMetrics: () => ipcRenderer.invoke('get-advanced-metrics'),
  exportReport: (options) => ipcRenderer.invoke('export-report', options),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  saveTrainingPlan: (plan) => ipcRenderer.invoke('save-training-plan', plan),
  getTrainingPlan: () => ipcRenderer.invoke('get-training-plan'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  updateSetting: (key, value) => ipcRenderer.invoke('update-setting', key, value),
  importStrava: (opts) => ipcRenderer.invoke('import-strava', opts),
  refreshStravaToken: (opts) => ipcRenderer.invoke('refresh-strava-token', opts)
  ,
  // Water + training helpers
  dailyResetWater: () => ipcRenderer.invoke('daily-reset-water'),
  getWaterHistory: () => ipcRenderer.invoke('get-water-history'),
  addWaterDay: (date, glasses, liters) => ipcRenderer.invoke('add-water-day', date, glasses, liters),
  getRecommendedWater: () => ipcRenderer.invoke('get-recommended-water'),
  saveTrainingPlan: (plan) => ipcRenderer.invoke('save-training-plan', plan),
  getTrainingPlan: (opts) => ipcRenderer.invoke('get-training-plan', opts)
  ,
  // Window controls for frameless window
  minimizeWindow: () => ipcRenderer.send('minimize-window'),
  maximizeWindow: () => ipcRenderer.send('maximize-window'),
  closeWindow: () => ipcRenderer.send('close-window')
});
